import type { PremiumBusiness } from "./PremiumBusinessRow";
import type { PopularBusiness } from "./PopularBusinessGrid";

export const verifiedBusinesses: PremiumBusiness[] = [
  {
    coverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=400&fit=crop",
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=console",
    name: "Console Kings",
    creator: "ConsoleKings",
    description: "#1 Competitive Call of Duty Gaming Platform | ConsoleKings.com",
    rating: undefined,
    members: "6.0k",
    views: "378",
    launchedAgo: "Launched 3mo ago",
    verified: "blue",
  },
  {
    coverImage: "https://images.unsplash.com/photo-1461896836934-bd45ba8c9e5a?w=600&h=400&fit=crop",
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=bravo",
    name: "Bravo Six Picks | Sports...",
    creator: "Bravo Six Picks",
    description: "Whop's #1 Highest Rated Sports Betting Group — 100% FREE 3 DAYS.",
    rating: 5.0,
    reviewCount: 1116,
    members: "7.1k",
    views: "272.1k",
    launchedAgo: "Launched 1y ago",
    verified: "blue",
  },
  {
    coverImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop",
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=athletic",
    name: "Athletic Army - Real Fitness",
    creator: "Alan Hanik",
    description: "I am a functional fitness coach helping motivated athletes to reach peak performance.",
    rating: 5.0,
    reviewCount: 9,
    members: "85",
    views: "15.1k",
    launchedAgo: "Launched 10mo ago",
    verified: "blue",
  },
  {
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop",
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=quarterly",
    name: "The Quarterly Science...",
    creator: "Mitch Griffin",
    description: "Former Wake Forest researcher covering deep science topics.",
    members: "577",
    views: "7.6k",
    verified: "blue",
  },
];

export const salesCommunityBusinesses: PremiumBusiness[] = [
  {
    coverImage: "https://images.unsplash.com/photo-1614854262318-831574f15f1f?w=600&h=400&fit=crop",
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=lions",
    name: "Lions Den",
    creator: "The Lion Glass",
    description: "If you are looking for a community that feels more like a last stand in a failing modern world - look ...",
    rating: 4.9,
    reviewCount: 122,
    members: "215",
    views: "19.6k",
    launchedAgo: "Launched 1y ago",
  },
  {
    coverImage: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&h=400&fit=crop",
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=linkedin",
    name: "LinkedIn Client Lab",
    creator: "Ty Frankel",
    description: "Join Ty Frankel's mastermind where 100+ B2B founders are signing 2-5+ clients/month.",
    rating: 5.0,
    reviewCount: 40,
    members: "113",
    views: "18.9k",
    launchedAgo: "Launched 1y ago",
  },
  {
    coverImage: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&h=400&fit=crop",
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=7level",
    name: "7th Level University",
    creator: "Jeremy Lee Miner",
    description: "Home Of The Worlds Largest Sales Training Company",
    rating: 4.7,
    reviewCount: 152,
    members: "3.1k",
    views: "18.1k",
    launchedAgo: "Launched 4mo ago",
  },
  {
    coverImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop",
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=fide",
    name: "Fidelity Masters",
    creator: "DSG",
    description: "DSG is the #1 community for 2,300 B2B sellers building real businesses.",
    rating: 5.0,
    reviewCount: 80,
    members: "1.2k",
    views: "12.4k",
  },
];

export const popularBusinesses: PopularBusiness[] = [
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=emoney",
    name: "eMoney",
    creator: "Nick from eMoney",
    description: "I've spent years mastering the art of finding hidden deals and price glitche...",
    rating: 4.8,
    reviewCount: 2580,
    members: "444.8k",
    views: "527.5k",
    launchedAgo: "3y ago",
    verified: "blue",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=whopai",
    name: "Whop AI",
    creator: "Connor",
    description: "Internal Whop AI company. We make generalist agents that help automate...",
    members: "310.8k",
    views: "29.4k",
    launchedAgo: "1mo ago",
    verified: "blue",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=mediametas",
    name: "Media Metas",
    creator: "musa",
    description: "I've dedicated my career to mastering social media growth. With Media Meta...",
    rating: 4.3,
    reviewCount: 770,
    members: "183.1k",
    views: "542.6k",
    launchedAgo: "2y ago",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=snewj",
    name: "SnewJ Props",
    creator: "SNEWJ PROPS",
    description: "With over a decade of experience, SnewJ Props shares Players Prop Pick...",
    rating: 4.6,
    reviewCount: 1634,
    members: "154.7k",
    views: "908.3k",
    launchedAgo: "2y ago",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=steven",
    name: "Steven's whop",
    creator: "steven s",
    description: "Some random shit that I like to sell",
    rating: 4.7,
    reviewCount: 92,
    members: "147.9k",
    views: "37.4k",
    launchedAgo: "3y ago",
    verified: "blue",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=crystal",
    name: "Crystal Academy",
    creator: "Sierra Smith",
    description: "I've built Crystal Academy to demystify trading. From live sessions to exclusiv...",
    rating: 4.8,
    reviewCount: 2806,
    members: "143.6k",
    views: "606.8k",
    launchedAgo: "2y ago",
    verified: "blue",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=tms",
    name: "Trust My System",
    creator: "Trustmysystem",
    description: "TMS Sports Consulting LLC specializes in American sports, focusing on qualit...",
    rating: 4.8,
    reviewCount: 4270,
    members: "140.0k",
    views: "1.9M",
    launchedAgo: "2y ago",
    verified: "blue",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=prosports",
    name: "Pro Sports Advice",
    creator: "Pro Sports Advice",
    description: "As a 11-year professional gambler, I created my Whop to share expert spor...",
    rating: 4.8,
    reviewCount: 1508,
    members: "139.8k",
    views: "843.9k",
    launchedAgo: "1y ago",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=potion",
    name: "Potion Alpha",
    creator: "Orangie",
    description: "I'm Orangie, the founder of Potion Alpha, the #1 online crypto platform...",
    rating: 4.8,
    reviewCount: 377,
    members: "121.5k",
    views: "759.4k",
    launchedAgo: "1y ago",
    verified: "blue",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=schoolof",
    name: "The School of...",
    creator: "Dontez Akram",
    description: "I've built a thriving e-commerce & investing community of over 3,900...",
    rating: 4.8,
    reviewCount: 382,
    members: "106.6k",
    views: "70.9k",
    launchedAgo: "3y ago",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=kingdom",
    name: "THE KINGDM",
    creator: "mambafx",
    description: "I've mastered the Forex market, turning trades into triumphs. Join me as I guid...",
    rating: 4.9,
    reviewCount: 899,
    members: "102.5k",
    views: "566.3k",
    launchedAgo: "2y ago",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=profit",
    name: "Profit Insider",
    creator: "Profit Insider",
    description: "RP is a trader and entrepreneur dedicated to mastering financial...",
    rating: 4.9,
    reviewCount: 293,
    members: "91.8k",
    views: "273.9k",
    launchedAgo: "2y ago",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=kingcap",
    name: "KingCapSports",
    creator: "KingCapSports",
    description: "4th Generation Las Vegas Sharp. Providing professional sports...",
    rating: 4.8,
    reviewCount: 3285,
    members: "74.6k",
    views: "520.2k",
    launchedAgo: "2y ago",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=beatbooks",
    name: "Beat the Books",
    creator: "Beat the Books",
    description: "Founded in 2022, Beat the Books is one of the largest sports capping...",
    rating: 4.6,
    reviewCount: 1749,
    members: "70.1k",
    views: "748.1k",
    launchedAgo: "3y ago",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=official",
    name: "Official Picks",
    creator: "Official Picks",
    description: "The #1 sports picks community on Whop. 3,600+ reviews. 66,000+...",
    rating: 4.8,
    reviewCount: 3777,
    members: "67.9k",
    views: "274.5k",
    launchedAgo: "2y ago",
  },
  {
    profileImage: "https://api.dicebear.com/7.x/shapes/svg?seed=goldpips",
    name: "GOLD PIPS",
    creator: "GoldPips",
    description: "Forex, Gold Trading signals",
    rating: 4.9,
    reviewCount: 289,
    members: "53.8k",
    views: "209.4k",
    launchedAgo: "11mo ago",
  },
];
