/**
 * Builder AI Image Enrichment
 * 
 * After text content is generated by AI, this utility scans the schema for
 * empty image slots and generates real AI images via ada-generate-image.
 * Images are uploaded to builder-media bucket and become permanent public URLs.
 * 
 * Cap: max 4 images per section fill to keep UX responsive.
 * Failures are silent — text content is preserved even if images fail.
 */

import { supabase } from "@/integrations/supabase/client";

/** Surface-type-specific image prompt context */
const IMAGE_CONTEXT: Record<string, string> = {
  eshop: "Professional ecommerce product photography, clean white background, studio lighting",
  store_listing: "Commercial catalog product photography, wholesale industrial style, clean background",
  emenu: "Professional food photography, appetizing plating, restaurant-quality, warm lighting",
  quick_site: "Professional business photography, modern corporate style, clean composition",
  live_bio: "Creator lifestyle photography, vibrant social media aesthetic, engaging visual",
  community_group: "Community event photography, diverse people, warm welcoming atmosphere",
  community_listing: "Community event photography, diverse people, warm welcoming atmosphere",
};

const AI_IMAGE_CAP_PER_SECTION = 4;

interface ImageSlot {
  path: string; // e.g. "media.url", "items.0.image_url", "items.2.src"
  prompt: string;
}

/**
 * Scan a generated schema for empty image fields and generate AI images.
 * Mutates the schema in-place with generated image URLs.
 * Returns the enriched schema (same reference).
 */
export async function enrichSchemaWithAiImages(
  schema: Record<string, unknown>,
  sectionType: string,
  surfaceType: string,
  userPrompt?: string,
): Promise<Record<string, unknown>> {
  const context = IMAGE_CONTEXT[surfaceType] || "Professional photography, clean composition";
  const slots: ImageSlot[] = [];

  // Check hero media
  if (sectionType === "hero") {
    const media = schema.media as Record<string, unknown> | undefined;
    const url = media?.url as string | undefined;
    if (!url || url === "" || isPlaceholder(url)) {
      const headline = (schema.headline as string) || "";
      slots.push({
        path: "media.url",
        prompt: `${context}. Hero banner: ${headline}. ${userPrompt || ""}`.trim(),
      });
    }
  }

  // Check items arrays
  const items = schema.items as Array<Record<string, unknown>> | undefined;
  if (Array.isArray(items)) {
    for (let i = 0; i < items.length && slots.length < AI_IMAGE_CAP_PER_SECTION; i++) {
      const item = items[i];
      if (!item || typeof item !== "object") continue;

      // Check image_url field (products, listings, featured)
      const imgUrl = item.image_url as string | undefined;
      if (imgUrl !== undefined && (!imgUrl || isPlaceholder(imgUrl))) {
        const name = (item.name as string) || (item.title as string) || `Item ${i + 1}`;
        const desc = (item.description as string) || "";
        slots.push({
          path: `items.${i}.image_url`,
          prompt: `${context}. ${name}. ${desc}`.trim(),
        });
        continue;
      }

      // Check src field (gallery)
      const srcUrl = item.src as string | undefined;
      if (srcUrl !== undefined && (!srcUrl || isPlaceholder(srcUrl))) {
        const name = (item.name as string) || (item.alt as string) || `Photo ${i + 1}`;
        slots.push({
          path: `items.${i}.src`,
          prompt: `${context}. ${name}. ${userPrompt || ""}`.trim(),
        });
      }
    }
  }

  if (slots.length === 0) return schema;

  if (import.meta.env.DEV) console.log(`[AI_IMAGE_ENRICH] Generating ${slots.length} images for ${sectionType}`);

  // Get session for auth
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) {
    console.warn("[AI_IMAGE_ENRICH] No session — skipping image generation");
    return schema;
  }

  // Generate images in parallel (capped)
  const results = await Promise.allSettled(
    slots.map(async (slot) => {
      try {
        const res = await supabase.functions.invoke("ada-generate-image", {
          body: { prompt: slot.prompt },
        });

        if (res.error) {
          console.warn(`[AI_IMAGE_ENRICH] Failed for ${slot.path}:`, res.error.message);
          return null;
        }

        const data = res.data as any;
        let imageUrl: string | null = null;

        // Extract URL from response (same logic as BuilderMediaPicker)
        if (data?.image_url) {
          imageUrl = data.image_url;
        } else if (data?.url) {
          imageUrl = data.url;
        }

        // If we got a signed URL from ada-media, re-upload to builder-media for permanence
        if (imageUrl && data?.storage_path) {
          try {
            const imgFetch = await fetch(imageUrl);
            if (imgFetch.ok) {
              const blob = await imgFetch.blob();
              const userId = session.user.id;
              const path = `${userId}/ai-section/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.png`;
              const { error: uploadErr } = await supabase.storage
                .from("builder-media")
                .upload(path, blob, { contentType: "image/png" });

              if (!uploadErr) {
                const { data: publicData } = supabase.storage
                  .from("builder-media")
                  .getPublicUrl(path);
                imageUrl = publicData.publicUrl;
              }
            }
          } catch {
            // Keep the signed URL as fallback
          }
        }

        return imageUrl ? { path: slot.path, url: imageUrl } : null;
      } catch (err) {
        console.warn(`[AI_IMAGE_ENRICH] Error for ${slot.path}:`, err);
        return null;
      }
    })
  );

  // Apply results to schema
  for (const r of results) {
    if (r.status !== "fulfilled" || !r.value) continue;
    const { path, url } = r.value;

    if (path === "media.url") {
      const media = (schema.media as Record<string, unknown>) || {};
      media.url = url;
      media.type = "image";
      media.fit = "cover";
      media.source = "ai";
      schema.media = media;
    } else if (path.startsWith("items.")) {
      const parts = path.split(".");
      const idx = parseInt(parts[1], 10);
      const key = parts[2]; // "image_url" or "src"
      const items = schema.items as Array<Record<string, unknown>>;
      if (Array.isArray(items) && idx < items.length) {
        items[idx][key] = url;
        items[idx].source = "ai";
      }
    }
  }

  const successCount = results.filter(r => r.status === "fulfilled" && r.value).length;
  if (import.meta.env.DEV) console.log(`[AI_IMAGE_ENRICH] ${successCount}/${slots.length} images generated successfully`);

  return schema;
}

function isPlaceholder(url: string): boolean {
  if (!url) return true;
  const lower = url.toLowerCase();
  return lower.includes("picsum") || lower.includes("placeholder") || lower.includes("example.com") || lower.includes("via.placeholder");
}
