import type { BuilderEngine } from "../types";

const CURRENCIES = [
  { value: "UGX", label: "UGX — Ugandan Shilling (UGX)" },
  { value: "USD", label: "USD — US Dollar ($)" },
  { value: "EUR", label: "EUR — Euro (€)" },
  { value: "GBP", label: "GBP — British Pound (£)" },
  { value: "KES", label: "KES — Kenyan Shilling" },
  { value: "TZS", label: "TZS — Tanzanian Shilling" },
  { value: "RWF", label: "RWF — Rwandan Franc" },
  { value: "NGN", label: "NGN — Nigerian Naira (₦)" },
  { value: "GHS", label: "GHS — Ghanaian Cedi (GH₵)" },
  { value: "ZAR", label: "ZAR — South African Rand (R)" },
  { value: "AED", label: "AED — UAE Dirham" },
  { value: "INR", label: "INR — Indian Rupee (₹)" },
  { value: "CNY", label: "CNY — Chinese Yuan (¥)" },
  { value: "JPY", label: "JPY — Japanese Yen (¥)" },
  { value: "CAD", label: "CAD — Canadian Dollar (CA$)" },
  { value: "AUD", label: "AUD — Australian Dollar (A$)" },
  { value: "BRL", label: "BRL — Brazilian Real (R$)" },
  { value: "MXN", label: "MXN — Mexican Peso (MX$)" },
  { value: "ETB", label: "ETB — Ethiopian Birr" },
  { value: "XOF", label: "XOF — West African CFA" },
  { value: "XAF", label: "XAF — Central African CFA" },
];

export const emenuEngine: BuilderEngine = {
  key: "emenu",
  surfaceType: "emenu",
  label: "Emenu",
  description: "Create a digital menu for your restaurant or food business.",
  publishDomain: "yangu.shop",
  icon: "Utensils",
  industries: [
    { value: "restaurant", label: "Restaurant" },
    { value: "cafe", label: "Cafe" },
    { value: "bakery", label: "Bakery" },
    { value: "ice_cream", label: "Ice Cream" },
    { value: "catering", label: "Catering" },
    { value: "bar_lounge", label: "Bar / Lounge" },
    { value: "food_truck", label: "Food Truck" },
    { value: "fast_food", label: "Fast Food" },
    { value: "fine_dining", label: "Fine Dining" },
    { value: "juice_bar", label: "Juice Bar" },
    { value: "coffee_shop", label: "Coffee Shop" },
    { value: "dessert_shop", label: "Dessert Shop" },
    { value: "pizza", label: "Pizza" },
    { value: "grill", label: "Grill" },
    { value: "buffet", label: "Buffet" },
    { value: "takeaway", label: "Takeaway" },
    { value: "delivery_kitchen", label: "Delivery Kitchen" },
  ],
  manualSteps: [
    {
      title: "Basic Information",
      subtitle: "Tell us about your food business",
      continueLabel: "Continue to Branding →",
      fields: [
        { key: "business_name", label: "Business Name", type: "text", placeholder: "e.g. Mama's Kitchen", required: true },
        { key: "slug", label: "Menu URL Slug", type: "slug", slugDomain: "yangu.shop", slugSource: "business_name", required: true, placeholder: "mamas-kitchen" },
        { key: "cuisine_type", label: "Cuisine Type", type: "text", placeholder: "e.g. African, Italian, Fusion" },
        { key: "menu_type", label: "Menu Type", type: "select", options: [
          { value: "qr_only", label: "QR Menu (view only)" },
          { value: "ordering", label: "Ordering Enabled" },
        ], defaultValue: "qr_only", hint: "Choose whether customers can place orders" },
        { key: "contact_email", label: "Contact Email", type: "email", placeholder: "hello@example.com", required: true, colSpan: 1 },
        { key: "contact_phone", label: "Contact Phone", type: "tel", placeholder: "+255...", required: true, colSpan: 1 },
        { key: "location", label: "Location Address", type: "text", placeholder: "123 Main St, Dar es Salaam" },
        { key: "currency", label: "Currency", type: "select", options: CURRENCIES, defaultValue: "UGX" },
      ],
    },
    {
      title: "Branding & Social",
      subtitle: "Upload your logo and set your brand style",
      continueLabel: "Continue to Settings →",
      fields: [
        { key: "logo_url", label: "Restaurant Logo", type: "file", hint: "Upload or generate with AI" },
        { key: "hero_banner_url", label: "Hero Banner (Optional)", type: "file", hint: "Banner image for the top of your menu" },
        { key: "primary_color", label: "Primary Brand Color", type: "color", defaultValue: "#b5622a" },
        { key: "layout_style", label: "Menu Layout Style", type: "select", options: [{ value: "grid", label: "Grid" }, { value: "list", label: "List" }], defaultValue: "grid", colSpan: 1 },
        { key: "logo_position", label: "Logo Position", type: "select", options: [{ value: "left", label: "Left" }, { value: "center", label: "Center" }], defaultValue: "left", colSpan: 1 },
        { key: "logo_size", label: "Logo Size", type: "select", options: [{ value: "small", label: "Small" }, { value: "medium", label: "Medium" }, { value: "large", label: "Large" }], defaultValue: "medium", colSpan: 1 },
        { key: "show_business_name", label: "Show Business Name", type: "switch", defaultValue: true, colSpan: 1 },
        { key: "social_website", label: "Website", type: "text", placeholder: "https://…" },
        { key: "social_instagram", label: "Instagram", type: "text", placeholder: "@handle" },
        { key: "social_facebook", label: "Facebook", type: "text", placeholder: "facebook.com/…" },
        { key: "social_twitter", label: "Twitter / X", type: "text", placeholder: "@handle" },
        { key: "social_tiktok", label: "TikTok", type: "text", placeholder: "@handle" },
      ],
    },
    {
      title: "Order & Payment Settings",
      subtitle: "Configure how customers order and pay",
      continueLabel: "Complete Setup & Create Menu ✓",
      fields: [
        { key: "order_dine_in", label: "Dine In", type: "checkbox", defaultValue: true },
        { key: "order_takeaway", label: "Takeaway", type: "checkbox" },
        { key: "order_delivery", label: "Delivery", type: "checkbox" },
        { key: "pay_cash", label: "Cash", type: "checkbox", defaultValue: true },
        { key: "pay_mobile_money", label: "Mobile Money", type: "checkbox" },
        { key: "mobile_money_number", label: "Mobile Money Number", type: "text", placeholder: "+255...", showIf: "pay_mobile_money" },
        { key: "mobile_money_name", label: "Registered Name", type: "text", placeholder: "Name on account", showIf: "pay_mobile_money" },
        { key: "pay_card", label: "Card / Stripe", type: "checkbox" },
        { key: "pay_paypal", label: "PayPal", type: "checkbox" },
      ],
    },
  ],
  aiQuestions: [
    { key: "business_name", label: "Restaurant/business name", type: "text", required: true, placeholder: "e.g. Mama's Kitchen" },
    { key: "cuisine_type", label: "Cuisine type", type: "text", placeholder: "e.g. African, Italian, Fusion" },
    { key: "menu_type", label: "Menu type", type: "text", placeholder: "QR only or ordering enabled?" },
    { key: "delivery_enabled", label: "Delivery available?", type: "text", placeholder: "Yes / No" },
    { key: "location", label: "Location", type: "text", placeholder: "City or area" },
  ],
  defaultSections: [
    { type: "hero", schema: { headline: "", subheadline: "", logo: "", logo_position: "left" } },
    { type: "menu", schema: { heading: "Menu", categories: [], layout_style: "grid", currency: "UGX", currency_symbol: "UGX" } },
    { type: "hours", schema: { heading: "Opening Hours", items: [] } },
    { type: "contact", schema: { heading: "Contact", email: "", phone: "", address: "" } },
  ],
  editorModules: ["menu_categories", "menu_items", "food_image_ai", "hours", "order_settings", "contact", "social"],
  templates: [
    { key: "hero_restaurant", label: "Hero Restaurant", sectionType: "hero", schema: { headline: "", subheadline: "", logo: "", logo_position: "left", banner: "" } },
    { key: "menu_categories", label: "Menu Categories", sectionType: "menu", schema: { heading: "Menu", categories: [], layout_style: "grid" } },
    { key: "featured_dishes", label: "Featured Dishes", sectionType: "featured", schema: { heading: "Featured", items: [] } },
    { key: "qr_menu", label: "QR Menu Card", sectionType: "qr", schema: { heading: "Scan to View Menu" } },
    { key: "offers_banner", label: "Offers Banner", sectionType: "offers", schema: { heading: "Today's Offers", items: [] } },
    { key: "reviews", label: "Customer Reviews", sectionType: "reviews", schema: { heading: "Reviews", items: [] } },
  ],
  aiGenerationRules: {
    allowedSectionTypes: ["hero", "menu", "featured", "hours", "contact", "offers", "reviews", "gallery", "qr"],
    forbiddenSectionTypes: ["booking", "listings", "products", "cart", "checkout", "bio", "links", "affiliate", "member_signup", "programs", "events"],
    generationHints: [
      "Generate sample menu structure with categories and items based on cuisine type",
      "Generate dish descriptions with appetizing language",
      "Suggest food images using AI food image generator",
      "Include opening hours section",
      "Never add booking calendar or property listings",
    ],
  },
};
