import type { BuilderEngine } from "../types";

export const esiteEngine: BuilderEngine = {
  key: "esite",
  surfaceType: "quick_site",
  label: "Esite",
  description: "Build a professional website for your business or service.",
  publishDomain: "yangu.site",
  icon: "Globe",
  industries: [
    { value: "agency", label: "Agency" },
    { value: "consultant", label: "Consultant" },
    { value: "clinic", label: "Clinic / Medical" },
    { value: "real_estate", label: "Real Estate" },
    { value: "car_dealer", label: "Car Dealer" },
    { value: "law_firm", label: "Law Firm" },
    { value: "school", label: "School / Education" },
    { value: "ngo", label: "NGO / Nonprofit" },
    { value: "finance", label: "Finance Advisor" },
    { value: "coach", label: "Coach / Trainer" },
    { value: "portfolio", label: "Portfolio / Freelancer" },
    { value: "hospitality", label: "Hotel / Hospitality" },
    { value: "salon_spa", label: "Salon / Spa" },
    { value: "gym_fitness", label: "Gym / Fitness" },
    { value: "church", label: "Church / Religious Org" },
    { value: "construction", label: "Construction" },
    { value: "logistics", label: "Logistics / Transport" },
    { value: "other", label: "Other" },
  ],
  manualSteps: [
    {
      title: "Business Information",
      subtitle: "Tell us about your business",
      continueLabel: "Continue to Branding →",
      fields: [
        { key: "business_name", label: "Business Name", type: "text", required: true, placeholder: "e.g. Acme Consulting" },
        { key: "slug", label: "Website URL Slug", type: "slug", slugDomain: "yangu.site", slugSource: "business_name", required: true },
        { key: "industry", label: "Industry", type: "select", options: [], required: true, hint: "Select your industry to get tailored sections" },
        { key: "business_description", label: "What does your business do?", type: "textarea", placeholder: "Brief description of your services…" },
        { key: "contact_email", label: "Contact Email", type: "email", placeholder: "hello@example.com", required: true, colSpan: 1 },
        { key: "contact_phone", label: "Contact Phone", type: "tel", placeholder: "+255...", colSpan: 1 },
        { key: "location", label: "Location", type: "text", placeholder: "City, Country" },
      ],
    },
    {
      title: "Branding",
      subtitle: "Set your visual identity",
      continueLabel: "Continue to Content →",
      fields: [
        { key: "logo_url", label: "Logo", type: "file", hint: "Upload or generate with AI" },
        { key: "primary_color", label: "Primary Brand Color", type: "color", defaultValue: "#2563eb" },
      ],
    },
    {
      title: "Content & Features",
      subtitle: "Choose what to include on your site",
      continueLabel: "Create Website ✓",
      fields: [
        { key: "include_about", label: "About Section", type: "switch", defaultValue: true },
        { key: "include_services", label: "Services Section", type: "switch", defaultValue: true },
        { key: "include_team", label: "Team Section", type: "switch" },
        { key: "include_testimonials", label: "Testimonials", type: "switch" },
        { key: "include_blog", label: "Blog", type: "switch" },
        { key: "include_contact", label: "Contact Form", type: "switch", defaultValue: true },
        { key: "include_faq", label: "FAQ Section", type: "switch" },
      ],
    },
  ],
  aiQuestions: [
    { key: "business_name", label: "Business name", type: "text", required: true, placeholder: "e.g. Acme Consulting" },
    { key: "industry", label: "Industry", type: "text", placeholder: "e.g. Real Estate, Law, Education" },
    { key: "business_description", label: "What do you do?", type: "textarea", placeholder: "Brief description" },
  ],
  defaultSections: [
    { type: "hero", schema: { headline: "", subheadline: "" } },
    { type: "text", schema: { heading: "About Us", body: "" } },
    { type: "text", schema: { heading: "Our Services", body: "" } },
    { type: "contact", schema: { heading: "Contact", email: "", phone: "" } },
  ],
  editorModules: ["hero", "text", "services", "team", "testimonials", "contact", "faq", "blog"],
  industryModules: {
    real_estate: ["listings", "property_filters"],
    hospitality: ["booking_calendar", "room_manager", "amenities"],
    clinic: ["booking_calendar", "services"],
    salon_spa: ["booking_calendar", "services"],
    gym_fitness: ["booking_calendar", "programs"],
  },
};
