import type { BuilderEngine } from "../types";

export const esiteEngine: BuilderEngine = {
  key: "esite",
  surfaceType: "quick_site",
  label: "Esite",
  description: "Build a professional website for your business or service.",
  publishDomain: "yangu.site",
  icon: "Globe",
  industries: [
    { value: "agency", label: "Agency" },
    { value: "consultant", label: "Consultant" },
    { value: "clinic", label: "Clinic / Medical" },
    { value: "real_estate", label: "Real Estate" },
    { value: "car_dealer", label: "Car Dealer" },
    { value: "law_firm", label: "Law Firm" },
    { value: "school", label: "School / Education" },
    { value: "ngo", label: "NGO / Nonprofit" },
    { value: "finance", label: "Finance Advisor" },
    { value: "coach", label: "Coach / Trainer" },
    { value: "portfolio", label: "Portfolio / Freelancer" },
    { value: "hospitality", label: "Hotel / Hospitality" },
    { value: "salon_spa", label: "Salon / Spa" },
    { value: "gym_fitness", label: "Gym / Fitness" },
    { value: "church", label: "Church / Religious Org" },
    { value: "construction", label: "Construction" },
    { value: "logistics", label: "Logistics / Transport" },
    { value: "other", label: "Other" },
  ],
  manualSteps: [
    {
      title: "Business Information",
      subtitle: "Tell us about your business",
      continueLabel: "Continue to Branding →",
      fields: [
        { key: "business_name", label: "Business Name", type: "text", required: true, placeholder: "e.g. Acme Consulting" },
        { key: "slug", label: "Website URL Slug", type: "slug", slugDomain: "yangu.site", slugSource: "business_name", required: true },
        { key: "industry", label: "Industry", type: "select", options: [], required: true, hint: "Select your industry to get tailored sections" },
        { key: "business_description", label: "What does your business do?", type: "textarea", placeholder: "Brief description of your services…" },
        { key: "services_offered", label: "Services Offered", type: "textarea", placeholder: "List your main services, comma separated" },
        { key: "contact_email", label: "Contact Email", type: "email", placeholder: "hello@example.com", required: true, colSpan: 1 },
        { key: "contact_phone", label: "Contact Phone", type: "tel", placeholder: "+255...", colSpan: 1 },
        { key: "location", label: "Location", type: "text", placeholder: "City, Country" },
      ],
    },
    {
      title: "Branding",
      subtitle: "Set your visual identity",
      continueLabel: "Continue to Content →",
      fields: [
        { key: "logo_url", label: "Logo", type: "file", hint: "Upload or generate with AI" },
        { key: "primary_color", label: "Primary Brand Color", type: "color", defaultValue: "#2563eb" },
      ],
    },
    {
      title: "Content & Features",
      subtitle: "Choose what to include on your site",
      continueLabel: "Create Website ✓",
      fields: [
        { key: "include_about", label: "About Section", type: "switch", defaultValue: true },
        { key: "include_services", label: "Services Section", type: "switch", defaultValue: true },
        { key: "include_team", label: "Team Section", type: "switch" },
        { key: "include_testimonials", label: "Testimonials", type: "switch" },
        { key: "include_blog", label: "Blog", type: "switch" },
        { key: "include_contact", label: "Contact Form", type: "switch", defaultValue: true },
        { key: "include_faq", label: "FAQ Section", type: "switch" },
      ],
    },
  ],
  aiQuestions: [
    { key: "business_name", label: "Business name", type: "text", required: true, placeholder: "e.g. Acme Consulting" },
    { key: "industry", label: "Industry", type: "text", placeholder: "e.g. Real Estate, Law, Education" },
    { key: "business_description", label: "What do you do?", type: "textarea", placeholder: "Brief description" },
    { key: "services_offered", label: "Key services", type: "text", placeholder: "e.g. Web design, Branding, SEO" },
    { key: "location", label: "Location", type: "text", placeholder: "City or country" },
  ],
  defaultSections: [
    { type: "header", schema: { logo_url: "", logo_position: "left", logo_size: "medium", show_name: true, name_next_to_logo: true }, core_slot: "header" },
    { type: "hero", schema: { headline: "", subheadline: "" }, core_slot: "hero" },
    { type: "services", schema: { heading: "Services", items: [] }, core_slot: "main_content" },
    { type: "offer", schema: { heading: "What We Offer", description: "", items: [] }, core_slot: "offer" },
    { type: "footer", schema: { heading: "Footer", email: "", phone: "", address: "", hours: [], social: {} }, core_slot: "footer" },
  ],
  editorModules: ["hero", "text", "services", "team", "testimonials", "contact", "faq", "blog"],
  industryModules: {
    real_estate: ["listings", "property_filters"],
    hospitality: ["booking_calendar", "room_manager", "amenities", "date_availability"],
    clinic: ["booking_calendar", "services"],
    salon_spa: ["booking_calendar", "services"],
    gym_fitness: ["booking_calendar", "programs"],
  },
  conditionalQuestions: {
    real_estate: {
      extraSteps: [
        {
          title: "Real Estate Details",
          subtitle: "Configure your property listings",
          fields: [
            { key: "property_type", label: "Property Type", type: "select", options: [
              { value: "sale", label: "For Sale" },
              { value: "rent", label: "For Rent" },
              { value: "both", label: "Sale & Rent" },
            ], required: true },
            { key: "areas_served", label: "Areas Served", type: "text", placeholder: "e.g. Kampala, Entebbe, Jinja" },
            { key: "listings_estimate", label: "How many listings?", type: "select", options: [
              { value: "1-10", label: "1–10" },
              { value: "11-50", label: "11–50" },
              { value: "50+", label: "50+" },
            ] },
            { key: "inquiry_cta", label: "Inquiry Button Text", type: "text", placeholder: "e.g. Request Viewing", defaultValue: "Inquire Now" },
          ],
        },
      ],
      extraModules: ["listings", "property_cards", "property_filters"],
    },
    hospitality: {
      extraSteps: [
        {
          title: "Hospitality Details",
          subtitle: "Set up rooms and booking",
          fields: [
            { key: "booking_enabled", label: "Enable Online Booking?", type: "switch", defaultValue: true },
            { key: "room_types", label: "Room Types", type: "textarea", placeholder: "e.g. Standard, Deluxe, Suite" },
            { key: "room_sizes", label: "Room Sizes / Capacity", type: "text", placeholder: "e.g. 1-2 guests, 2-4 guests" },
            { key: "pricing_range", label: "Price Range", type: "text", placeholder: "e.g. $50 – $200 per night" },
            { key: "amenities", label: "Amenities", type: "textarea", placeholder: "e.g. WiFi, Pool, Gym, Parking" },
            { key: "availability_model", label: "Availability Model", type: "select", options: [
              { value: "calendar", label: "Calendar-based" },
              { value: "request", label: "Request-based" },
              { value: "always", label: "Always Available" },
            ], defaultValue: "calendar" },
          ],
        },
      ],
      extraModules: ["booking_calendar", "room_manager", "date_availability", "amenities"],
    },
  },
  templates: [
    { key: "hero_service", label: "Hero Service", sectionType: "hero", schema: { headline: "", subheadline: "", cta_label: "Get Started" } },
    { key: "service_grid", label: "Service Grid", sectionType: "services", schema: { heading: "Our Services", items: [], layout: "grid" } },
    { key: "testimonials", label: "Testimonials", sectionType: "testimonials", schema: { heading: "What Our Clients Say", items: [] } },
    { key: "booking_block", label: "Booking Block", sectionType: "booking", schema: { heading: "Book Now", mode: "calendar" } },
    { key: "listings_grid", label: "Listings Grid", sectionType: "listings", schema: { heading: "Properties", items: [], filters: true } },
    { key: "team_grid", label: "Team Grid", sectionType: "team", schema: { heading: "Our Team", members: [] } },
    { key: "faq_accordion", label: "FAQ Accordion", sectionType: "faq", schema: { heading: "FAQ", items: [] } },
  ],
  aiGenerationRules: {
    allowedSectionTypes: ["hero", "text", "services", "team", "testimonials", "contact", "faq", "blog", "cta", "gallery"],
    forbiddenSectionTypes: ["menu", "products", "cart", "checkout", "bio", "links", "affiliate", "live_selling", "member_signup"],
    generationHints: [
      "Generate professional service-oriented content",
      "If real_estate industry, include listings section with property cards",
      "If hospitality industry, include booking block and room showcase",
      "Focus on trust signals: testimonials, team, credentials",
    ],
  },
};
