import type { BuilderEngine } from "../types";

export const estoreEngine: BuilderEngine = {
  key: "estore",
  surfaceType: "store_listing",
  label: "Estore",
  description: "Create a store listing for wholesale, trading, or bulk business.",
  publishDomain: "yangu.store",
  icon: "Warehouse",
  industries: [
    { value: "trading", label: "Trading" },
    { value: "wholesale", label: "Wholesale" },
    { value: "distribution", label: "Distribution" },
    { value: "agriculture", label: "Agriculture Inputs" },
    { value: "construction", label: "Construction Materials" },
    { value: "supermarket", label: "Supermarket" },
    { value: "hardware", label: "Hardware Supplies" },
    { value: "bulk_supplier", label: "Bulk Supplier" },
    { value: "industrial", label: "Industrial Supplies" },
    { value: "other", label: "Other" },
  ],
  manualSteps: [
    {
      title: "Store Information",
      subtitle: "Tell us about your store or trading business",
      continueLabel: "Continue to Branding →",
      fields: [
        { key: "business_name", label: "Store / Company Name", type: "text", required: true, placeholder: "e.g. ABC Distributors" },
        { key: "slug", label: "Store URL Slug", type: "slug", slugDomain: "yangu.store", slugSource: "business_name", required: true },
        { key: "industry", label: "Industry", type: "select", options: [], required: true },
        { key: "business_model", label: "Business Model", type: "select", options: [
          { value: "wholesale", label: "Wholesale" },
          { value: "trading", label: "Trading" },
          { value: "both", label: "Wholesale & Trading" },
        ], required: true },
        { key: "business_description", label: "What do you supply?", type: "textarea", placeholder: "Products and services…" },
        { key: "product_volume", label: "Product Volume", type: "select", options: [
          { value: "small", label: "Under 50 SKUs" },
          { value: "medium", label: "50–500 SKUs" },
          { value: "large", label: "500+ SKUs" },
        ] },
        { key: "contact_email", label: "Contact Email", type: "email", required: true, colSpan: 1 },
        { key: "contact_phone", label: "Contact Phone", type: "tel", colSpan: 1 },
        { key: "location", label: "Location / Warehouse Address", type: "text" },
      ],
    },
    {
      title: "Branding",
      subtitle: "Set your store's visual identity",
      continueLabel: "Continue to Settings →",
      fields: [
        { key: "logo_url", label: "Company Logo", type: "file", hint: "Upload or generate with AI" },
        { key: "primary_color", label: "Primary Color", type: "color", defaultValue: "#0d9488" },
      ],
    },
    {
      title: "Pricing & Quoting",
      subtitle: "Configure pricing tiers and quoting",
      continueLabel: "Create Store ✓",
      fields: [
        { key: "enable_bulk_pricing", label: "Show Bulk Pricing Tiers", type: "switch", defaultValue: true, hint: "Display tiered pricing for volume orders" },
        { key: "enable_quotes", label: "Enable Quote Requests", type: "switch", defaultValue: true, hint: "Let buyers request custom quotes" },
        { key: "enable_partner_accounts", label: "Partner / Dealer Accounts", type: "switch", hint: "Allow approved partners to see special pricing" },
        { key: "min_order_value", label: "Minimum Order Value", type: "text", placeholder: "e.g. 100,000" },
        { key: "pay_bank_transfer", label: "Bank Transfer", type: "checkbox", defaultValue: true },
        { key: "pay_mobile_money", label: "Mobile Money", type: "checkbox" },
      ],
    },
  ],
  aiQuestions: [
    { key: "business_name", label: "Company name", type: "text", required: true },
    { key: "business_model", label: "Wholesale or trading?", type: "text", placeholder: "e.g. Wholesale, Trading, Both" },
    { key: "industry", label: "What do you trade/supply?", type: "text", placeholder: "e.g. Building materials, Agriculture" },
    { key: "product_volume", label: "Product volume scale", type: "text", placeholder: "e.g. Under 50, 50-500, 500+" },
    { key: "location", label: "Location", type: "text" },
  ],
  defaultSections: [
    { type: "header", schema: { logo_url: "", logo_position: "left", logo_size: "medium", show_name: true, name_next_to_logo: true }, core_slot: "header" },
    { type: "hero", schema: { headline: "", subheadline: "Your trusted supplier" }, core_slot: "hero" },
    { type: "listings", schema: { heading: "Listings", items: [] }, core_slot: "main_content" },
    { type: "offer", schema: { heading: "What We Offer", description: "", items: [] }, core_slot: "offer" },
    { type: "footer", schema: { heading: "Footer", email: "", phone: "", address: "", hours: [], social: {} }, core_slot: "footer" },
  ],
  editorModules: ["products", "catalog", "bulk_pricing", "quote_request", "large_inventory", "supplier_info", "contact"],
  templates: [
    { key: "hero_store", label: "Hero Store", sectionType: "hero", schema: { headline: "", subheadline: "", cta_label: "Request Quote" } },
    { key: "catalog_grid", label: "Product Catalog", sectionType: "products", schema: { heading: "Catalog", items: [], layout: "grid", filters: true } },
    { key: "bulk_pricing_table", label: "Bulk Pricing Table", sectionType: "bulk_pricing", schema: { heading: "Volume Pricing", tiers: [] } },
    { key: "quote_form", label: "Quote Request Form", sectionType: "quote", schema: { heading: "Request a Quote" } },
    { key: "supplier_info", label: "Supplier Info Block", sectionType: "supplier", schema: { heading: "About Us", certifications: [], partnerships: [] } },
  ],
  aiGenerationRules: {
    allowedSectionTypes: ["hero", "products", "bulk_pricing", "text", "contact", "gallery", "cta", "quote", "supplier"],
    forbiddenSectionTypes: ["menu", "booking", "listings", "bio", "links", "affiliate", "live_selling", "member_signup", "programs", "events", "cart", "checkout"],
    generationHints: [
      "Generate catalog layout with product categories",
      "Include bulk pricing tiers section",
      "Focus on B2B trust: certifications, partnerships, volume capacity",
      "Never add consumer cart/checkout — use quote request instead",
    ],
  },
};
