import type { BuilderEngine } from "../types";

export const influencerEngine: BuilderEngine = {
  key: "influencer",
  surfaceType: "live_bio",
  label: "Influencer",
  description: "Create your bio link page and connect with your audience.",
  publishDomain: "yangu.live",
  icon: "Star",
  industries: [
    { value: "fitness", label: "Fitness & Health" },
    { value: "beauty", label: "Beauty & Skincare" },
    { value: "sports", label: "Sports" },
    { value: "tech", label: "Tech & Gadgets" },
    { value: "lifestyle", label: "Lifestyle" },
    { value: "gaming", label: "Gaming" },
    { value: "education", label: "Education" },
    { value: "fashion", label: "Fashion" },
    { value: "comedy", label: "Comedy & Entertainment" },
    { value: "travel", label: "Travel" },
    { value: "food", label: "Food & Cooking" },
    { value: "music", label: "Music" },
    { value: "art", label: "Art & Design" },
    { value: "other", label: "Other" },
  ],
  manualSteps: [
    {
      title: "Your Profile",
      subtitle: "Tell us about yourself",
      continueLabel: "Continue to Social →",
      fields: [
        { key: "display_name", label: "Display Name / Stage Name", type: "text", required: true, placeholder: "e.g. @CreatorName" },
        { key: "slug", label: "Profile URL Slug", type: "slug", slugDomain: "yangu.live", slugSource: "display_name", required: true },
        { key: "niche", label: "Your Niche", type: "select", options: [], required: true, hint: "What content do you create?" },
        { key: "bio", label: "Short Bio", type: "textarea", placeholder: "Tell your audience who you are…" },
        { key: "main_platforms", label: "Main Platforms", type: "text", placeholder: "e.g. TikTok, Instagram, YouTube", hint: "Where are you most active?" },
        { key: "audience_location", label: "Audience Location", type: "text", placeholder: "e.g. East Africa, Global" },
        { key: "content_types", label: "Content Types", type: "text", placeholder: "e.g. Videos, Reels, Tutorials, Reviews" },
      ],
    },
    {
      title: "Social & Links",
      subtitle: "Connect your platforms",
      continueLabel: "Continue to Style →",
      fields: [
        { key: "avatar_url", label: "Profile Photo", type: "file" },
        { key: "link_instagram", label: "Instagram", type: "text", placeholder: "@handle" },
        { key: "link_tiktok", label: "TikTok", type: "text", placeholder: "@handle" },
        { key: "link_youtube", label: "YouTube", type: "text", placeholder: "Channel URL" },
        { key: "link_twitter", label: "Twitter / X", type: "text", placeholder: "@handle" },
        { key: "link_facebook", label: "Facebook", type: "text", placeholder: "Page URL" },
        { key: "link_website", label: "Website", type: "text", placeholder: "https://…" },
      ],
    },
    {
      title: "Style & Features",
      subtitle: "Customize your page look",
      continueLabel: "Create Profile ✓",
      fields: [
        { key: "primary_color", label: "Accent Color", type: "color", defaultValue: "#8b5cf6" },
        { key: "include_affiliate", label: "Affiliate Links Section", type: "switch", hint: "Add product recommendations" },
        { key: "affiliate_categories", label: "Affiliate Categories", type: "text", placeholder: "e.g. Fashion, Tech, Beauty", showIf: "include_affiliate" },
        { key: "include_media", label: "Media / Shorts Section", type: "switch", defaultValue: true, hint: "Showcase your latest content" },
        { key: "include_live_selling", label: "Live Selling", type: "switch", hint: "Pin products during live streams" },
        { key: "include_tips", label: "Tips / Support Section", type: "switch", hint: "Let fans support you" },
        { key: "include_contact", label: "Contact / Booking", type: "switch", defaultValue: true },
      ],
    },
  ],
  aiQuestions: [
    { key: "display_name", label: "Your name / handle", type: "text", required: true },
    { key: "niche", label: "What content do you create?", type: "text", placeholder: "e.g. Fitness tips, Beauty tutorials" },
    { key: "main_platforms", label: "Main platforms", type: "text", placeholder: "e.g. Instagram, TikTok, YouTube" },
    { key: "audience_location", label: "Audience location", type: "text", placeholder: "e.g. East Africa, Global" },
    { key: "content_types", label: "Content types", type: "text", placeholder: "e.g. Videos, Reels, Reviews" },
    { key: "affiliate_products", label: "Affiliate products?", type: "text", placeholder: "e.g. Yes — Fashion & Beauty" },
  ],
  defaultSections: [
    { type: "header", schema: { logo_url: "", logo_position: "center", logo_size: "large", show_name: true, name_next_to_logo: false, bio_mode: true, avatar_style: "circle_large", social_icons_position: "below_name", layout_variant: "link_bio_header" }, core_slot: "header" },
    { type: "hero", schema: { headline: "", subheadline: "", layout_variant: "link_bio_profile", avatar_enabled: true, social_row_enabled: true, search_enabled: true, typography_style: "creator_centered", media: { type: "image", source: "url", url: "", fit: "cover" } }, core_slot: "hero" },
    { type: "social", schema: { social_links: {}, disabled_links: [], active_social_links: [{ platform: "facebook", url: "", slotIndex: 0 }, { platform: "tiktok", url: "", slotIndex: 1 }, { platform: "instagram", url: "", slotIndex: 2 }, { platform: "snapchat", url: "", slotIndex: 3 }, { platform: "whatsapp", url: "", slotIndex: 4 }, { platform: "youtube", url: "", slotIndex: 5 }], icon_style: "original" }, core_slot: "social_icons" },
    { type: "links", schema: { items: [], display_mode: "link_buttons" }, core_slot: "main_content" },
    { type: "showcase", schema: { showcase_items: [], showcase_display: "carousel", heading: "My Picks" }, core_slot: "showcase" },
    { type: "offer", schema: { heading: "", description: "", items: [], layout_variant: "link_bio_gallery", display_mode: "link_bio_gallery", newsletter: { enabled: true, heading: "Let's stay in touch", cta_text: "Submit" } }, core_slot: "offer" },
    { type: "footer", schema: { heading: "", email: "", phone: "", address: "", hours: [], social: {}, layout_variant: "link_bio_footer", display_mode: "link_bio_footer" }, core_slot: "footer" },
  ],
  editorModules: ["bio", "links", "media", "affiliate", "live_product_pins", "tips", "contact"],
  templates: [
    { key: "bio_hero", label: "Bio Hero", sectionType: "hero", schema: { headline: "", subheadline: "", avatar: "" } },
    { key: "social_links", label: "Social Links", sectionType: "links", schema: { items: [] } },
    { key: "featured_products", label: "Featured Products", sectionType: "affiliate", schema: { heading: "My Picks", items: [] } },
    { key: "media_feed", label: "Media Feed", sectionType: "media", schema: { heading: "Latest Content", items: [] } },
    { key: "live_blocks", label: "Live Blocks", sectionType: "live", schema: { heading: "Live Now", pins: [] } },
    { key: "tip_jar", label: "Support Me", sectionType: "tips", schema: { heading: "Support", message: "" } },
  ],
  aiGenerationRules: {
    allowedSectionTypes: ["hero", "bio", "links", "media", "affiliate", "live", "tips", "contact", "cta"],
    forbiddenSectionTypes: ["menu", "products", "cart", "checkout", "booking", "listings", "services", "team", "faq", "blog", "bulk_pricing", "quotes", "member_signup", "programs", "events"],
    generationHints: [
      "Generate bio structure and creator-focused blocks",
      "Focus on social links and media showcase",
      "Never add business services, booking calendars, or product catalogs",
      "Never add community member signup or programs",
      "Keep layout social-first and mobile-optimized",
    ],
  },
};
