/** Human-readable labels for builder section types */
export const SECTION_TYPE_LABELS: Record<string, string> = {
  hero: "Hero Banner",
  header: "Header / Logo",
  bio: "Bio",
  links: "Links",
  social: "Socials",
  cta: "CTA",
  video: "Video",
  gallery: "Gallery",
  text: "Text",
  products: "Products",
  services: "Services",
  testimonials: "Testimonials",
  contact: "Contact",
  faq: "FAQ",
  menu: "Menu",
  schedule: "Schedule",
  offer: "Offers",
  hours: "Opening Hours",
  location: "Location",
  about: "About",
  plans: "Plans",
  featured: "Featured",
  join: "Join",
  listings: "Listings",
  footer: "Footer",
  properties: "Properties",
  rooms: "Rooms",
  booking_calendar: "Booking",
  programs: "Programs",
  tours: "Tours",
  team: "Team",
  services_pricing: "Services & Pricing",
  featured_products: "Featured Products",
  deals: "Deals",
  flash_sale: "Flash Sale",
  reviews: "Reviews",
  supplier_catalog: "Supplier Catalog",
  bulk_products: "Bulk Products",
  agriculture_produce: "Agriculture",
  manufacturer_products: "Manufacturer",
  coaching: "Coaching",
  courses: "Courses",
  live_webinars: "Live Webinars",
  workshops: "Workshops",
  mentorship: "Mentorship",
  resources: "Resources",
  discussions: "Discussions",
  live_stream: "Live Stream",
  live_selling: "Live Selling",
  affiliate_products: "Affiliate Products",
  media_feed: "Media Feed",
  merch: "Merch",
  tips_support: "Tips & Support",
  collabs: "Collabs",
};
