export interface CategoryGroup {
  label: string;
  subcategories: string[];
}

export const PRODUCT_CATEGORIES: CategoryGroup[] = [
  {
    label: "Agriculture & Farming",
    subcategories: [
      "Fresh Vegetables",
      "Fruits & Produce",
      "Poultry & Livestock",
      "Fisheries & Aquaculture",
      "Grains & Cereals",
      "Organic Farming",
      "Agro-processing",
      "Farm Equipment",
      "Seeds & Fertilizers",
      "Local Food Markets",
    ],
  },
  {
    label: "Apparel & Accessories",
    subcategories: [
      "Bags",
      "Clothing Accessories",
      "High-end Jewelry",
      "Men's Clothing",
      "Men's Shoes",
      "Ordinary Jewelry",
      "Traditional & Ceremonial Clothing",
      "Watches",
      "Wearable Tech Devices",
      "Women's Clothing",
      "Women's Shoes",
      "Fashion Boutique",
      "Traditional Wear",
      "Ankara & Kitenge Clothing",
      "Tailoring Services",
      "Handmade Accessories",
      "Cultural Jewelry",
      "Local Designers",
    ],
  },
  {
    label: "Apps",
    subcategories: [
      "Audio & Video Players",
      "Business & Productivity",
      "Education",
      "Financial Services",
      "Health & Fitness",
      "Life & Leisure",
      "News & Reading",
      "Online Shopping",
      "Parenting",
      "Photography",
      "Social",
      "Travel",
      "Utilities",
    ],
  },
  {
    label: "Baby, Kids & Maternity",
    subcategories: [
      "Baby Bedding",
      "Baby Feeding Supplies",
      "Baby Food",
      "Baby Formula",
      "Baby Hygiene Products",
      "Baby Shoes",
      "Child Car Seats",
      "Children's Apparel",
      "Diapers & Baby Wipes",
      "Strollers & Cribs",
      "Toys for Kids",
    ],
  },
  {
    label: "Beauty & Personal Care",
    subcategories: [
      "Bath & Body",
      "Fragrances",
      "Hair Care",
      "Makeup",
      "Nail Care",
      "Oral Care",
      "Skin Care",
      "Tools & Accessories",
    ],
  },
  {
    label: "Business Services",
    subcategories: [
      "Accounting & Finance",
      "Advertising & Marketing",
      "Consulting",
      "Human Resources",
      "IT Services",
      "Legal Services",
      "Logistics & Shipping",
      "Real Estate Services",
      "Street Vendors",
      "Local Markets",
      "Mobile Retail",
      "Artisan Crafts",
      "Beauty Salons",
      "Barbershops",
      "Food Stalls",
      "Community Shops",
      "Repair Services",
    ],
  },
  {
    label: "Creative & Handmade",
    subcategories: [
      "Handmade Bags",
      "Leather Goods",
      "Wood Crafts",
      "Sculpture",
      "Textile Art",
      "Cultural Decor",
      "Handmade Shoes",
    ],
  },
  {
    label: "E-Commerce",
    subcategories: [
      "Dropshipping",
      "Marketplace",
      "Online Retail",
      "Subscription Boxes",
    ],
  },
  {
    label: "Education",
    subcategories: [
      "Courses & Tutorials",
      "E-Learning Platforms",
      "School Supplies",
      "Test Preparation",
      "Textbooks",
    ],
  },
  {
    label: "Financial Services",
    subcategories: [
      "Commercial Banks",
      "Credit Bureaus",
      "Credit Cards",
      "Crowd Funding",
      "Cryptocurrencies",
      "Foreign Exchange Transactions",
      "Funds",
      "Guarantees",
      "Insurance",
      "Investment Advisory",
      "Loan Services",
      "Microfinance Companies",
      "Pawn Shops",
      "Precious Metals",
      "Securities",
      "Third-Party Payments",
      "Trusts",
    ],
  },
  {
    label: "Food & Beverage",
    subcategories: [
      "Beverages",
      "Canned & Packaged Food",
      "Dairy Products",
      "Fresh Food",
      "Frozen Food",
      "Snacks & Confectionery",
    ],
  },
  {
    label: "Games",
    subcategories: [
      "Board Games",
      "Console Games",
      "Mobile Games",
      "PC Games",
      "VR Games",
    ],
  },
  {
    label: "Health",
    subcategories: [
      "Fitness Equipment",
      "Medical Devices",
      "Nutrition & Supplements",
      "Personal Health Care",
      "Pharmacy",
    ],
  },
  {
    label: "Home Improvement",
    subcategories: [
      "Building Materials",
      "Electrical",
      "Flooring",
      "Hardware",
      "Lighting",
      "Paint & Wall Treatments",
      "Plumbing",
      "Tools",
    ],
  },
  {
    label: "Household Products",
    subcategories: [
      "Cleaning Supplies",
      "Home Decor",
      "Kitchen & Dining",
      "Laundry",
      "Storage & Organization",
    ],
  },
  {
    label: "Life Services",
    subcategories: [
      "Catering",
      "Cleaning Services",
      "Event Planning",
      "Moving Services",
      "Personal Care Services",
    ],
  },
  {
    label: "News & Entertainment",
    subcategories: [
      "Books & Magazines",
      "Movies & TV",
      "Music",
      "News Media",
      "Podcasts",
      "Streaming Services",
    ],
  },
  {
    label: "Others",
    subcategories: [
      "General",
      "Miscellaneous",
    ],
  },
  {
    label: "Pets",
    subcategories: [
      "Pet Accessories",
      "Pet Food",
      "Pet Grooming",
      "Pet Health",
      "Pet Toys",
    ],
  },
  {
    label: "Sports & Outdoors",
    subcategories: [
      "Camping & Hiking",
      "Cycling",
      "Exercise & Fitness",
      "Outdoor Recreation",
      "Sports Equipment",
      "Team Sports",
      "Water Sports",
    ],
  },
  {
    label: "Tech & Electronics",
    subcategories: [
      "Audio Equipment",
      "Cameras & Photography",
      "Computer Accessories",
      "Computers & Laptops",
      "Mobile Phones",
      "Smart Home",
      "Tablets",
      "Wearable Technology",
    ],
  },
  {
    label: "Travel",
    subcategories: [
      "Accommodation",
      "Car Rental",
      "Flights",
      "Luggage & Travel Gear",
      "Tours & Activities",
      "Travel Insurance",
    ],
  },
  {
    label: "Vehicle & Transportation",
    subcategories: [
      "Auto Parts & Accessories",
      "Car Care",
      "Electric Vehicles",
      "Motorcycles",
      "Trucks & Commercial",
      "Vehicle Electronics",
    ],
  },
];
