// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Yangu user id, email, and OAuth client id.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      userId: ctx.getUserId(),
      email: ctx.getUserEmail(),
      clientId: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-surfaces.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !anon) throw new Error("Supabase env vars are not configured for this function.");
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_surfaces_default = defineTool2({
  name: "list_my_surfaces",
  title: "List my Yangu surfaces",
  description: "List the signed-in user's Yangu builder surfaces (eshop, estore, emenu, esite, etc.) with title, slug, type, status, and published URL.",
  inputSchema: {
    limit: z.number().int().positive().max(100).optional().describe("Maximum number of surfaces to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("builder_surfaces").select("id, title, slug, surface_type, status, published_url, updated_at").is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const surfaces = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(surfaces, null, 2) }],
      structuredContent: { surfaces }
    };
  }
});

// src/lib/mcp/tools/get-surface.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !anon) throw new Error("Supabase env vars are not configured for this function.");
  return createClient2(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_surface_default = defineTool3({
  name: "get_surface",
  title: "Get a Yangu surface",
  description: "Fetch a single Yangu surface (by id or slug) owned by the signed-in user, including title, status, published URL, description and SEO metadata.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("Surface UUID."),
    slug: z2.string().optional().describe("Surface slug (used when id is not provided).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !slug) {
      return { content: [{ type: "text", text: "Provide either id or slug." }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("builder_surfaces").select(
      "id, title, slug, description, surface_type, status, published_url, seo_title, seo_description, updated_at, created_at"
    ).is("deleted_at", null).limit(1);
    query = id ? query.eq("id", id) : query.eq("slug", slug);
    const { data, error } = await query.maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Surface not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { surface: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xcipuyvcwfytlsjryhvs";
var mcp_default = defineMcp({
  name: "yangu-mcp",
  title: "Yangu",
  version: "0.1.0",
  instructions: "Tools for interacting with the signed-in user's Yangu account. Use `whoami` to verify the session, `list_my_surfaces` to see the user's builder surfaces (eshop, estore, emenu, esite, etc.), and `get_surface` for details of a single surface.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_surfaces_default, get_surface_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
