
INSERT INTO visionaire_product_requests (title, description, status, votes_count, is_active) VALUES
-- 10 more ideas (to reach 14 total)
('AI-Powered Newsletter Growth System', 'A comprehensive guide to using AI tools to grow and monetize your newsletter subscriber base.', 'idea', 12, true),
('The Pinterest Traffic Blueprint', 'Step-by-step system for driving massive organic traffic from Pinterest to your digital products.', 'idea', 9, true),
('Freelancer to Agency Transition Guide', 'How to scale from solo freelancer to running a profitable agency with systems and SOPs.', 'idea', 15, true),
('YouTube Shorts Monetization Playbook', 'Complete guide to creating, growing, and monetizing YouTube Shorts for digital entrepreneurs.', 'idea', 7, true),
('The Cold Email Outreach System', 'Templates and strategies for B2B cold email that actually converts into clients.', 'idea', 11, true),
('Build Your First Chrome Extension', 'Developer-friendly guide to building and monetizing Chrome extensions as a side business.', 'idea', 6, true),
('Community-Led Growth Handbook', 'How to build and leverage online communities to grow your brand and revenue.', 'idea', 18, true),
('The Webinar Sales Machine', 'End-to-end system for creating high-converting webinars that sell digital products.', 'idea', 8, true),
('Passive Income with Print on Demand', 'Complete guide to building a profitable print-on-demand business from scratch.', 'idea', 14, true),
('The LinkedIn Content Creator Playbook', 'Strategies for building authority and generating leads through LinkedIn content.', 'idea', 10, true),
-- 43 more planned (to reach 46 total)
('The Podcast Launch Formula', 'Everything you need to plan, launch, and grow a successful podcast.', 'planned', 22, true),
('Instagram Reels Mastery', 'Create viral Reels that grow your following and drive sales.', 'planned', 19, true),
('The Affiliate Marketing Blueprint', 'Build a sustainable affiliate marketing business with proven strategies.', 'planned', 31, true),
('SaaS Marketing for Bootstrappers', 'Growth marketing playbook specifically for self-funded SaaS founders.', 'planned', 16, true),
('The Remote Team Management Guide', 'Best practices for hiring, managing, and scaling remote teams.', 'planned', 24, true),
('Notion for Business Operations', 'Transform your business operations with advanced Notion systems.', 'planned', 13, true),
('The Ghostwriting Business Model', 'How to start and scale a profitable ghostwriting business.', 'planned', 17, true),
('Digital Product Photography Guide', 'Create professional product photos using just your smartphone.', 'planned', 11, true),
('The TikTok Ads Playbook', 'Master TikTok advertising for e-commerce and digital products.', 'planned', 28, true),
('Building a Personal CRM System', 'Organize and leverage your professional network systematically.', 'planned', 9, true),
('The Subscription Box Business Guide', 'Launch and scale a profitable subscription box business.', 'planned', 14, true),
('AI Tools for Content Repurposing', 'Maximize content output by repurposing across all platforms with AI.', 'planned', 26, true),
('The Etsy Seller Success Guide', 'From opening your shop to scaling to six figures on Etsy.', 'planned', 20, true),
('Copywriting Frameworks That Convert', 'Battle-tested copywriting frameworks for ads, emails, and landing pages.', 'planned', 33, true),
('The Creator Economy Handbook', 'Navigate the creator economy and build sustainable income streams.', 'planned', 15, true),
('Facebook Ads for Digital Products', 'Profitable Facebook ad strategies specifically for digital product sellers.', 'planned', 21, true),
('The Productized Service Blueprint', 'Turn your service business into scalable productized offerings.', 'planned', 18, true),
('Building a Knowledge Base Business', 'Create and monetize comprehensive knowledge bases and wikis.', 'planned', 8, true),
('The Sales Funnel Optimization Guide', 'A/B test and optimize every stage of your sales funnel.', 'planned', 25, true),
('Influencer Collaboration Playbook', 'Find, negotiate, and partner with influencers to grow your brand.', 'planned', 12, true),
('The Digital Course Creation System', 'Create, launch, and sell online courses that generate passive income.', 'planned', 29, true),
('Canva Design Mastery for Entrepreneurs', 'Create professional-grade designs without hiring a designer.', 'planned', 10, true),
('The Membership Site Blueprint', 'Build and grow a recurring revenue membership community.', 'planned', 23, true),
('Google Ads for Beginners', 'Step-by-step guide to profitable Google Ads campaigns.', 'planned', 17, true),
('The Virtual Assistant Business Guide', 'Start and scale a virtual assistant business from anywhere.', 'planned', 7, true),
('Email List Building Masterclass', 'Proven tactics to grow your email list from 0 to 10,000 subscribers.', 'planned', 30, true),
('The White Label Digital Products Guide', 'Create and sell white label products for passive income.', 'planned', 11, true),
('Shopify Store Optimization Handbook', 'Increase conversions and AOV with advanced Shopify optimization.', 'planned', 19, true),
('The Micro-SaaS Starter Kit', 'Build and launch a micro-SaaS product as a solo founder.', 'planned', 27, true),
('Brand Storytelling for Small Business', 'Craft compelling brand narratives that connect with customers.', 'planned', 14, true),
('The Lead Magnet Library', 'Create irresistible lead magnets for every stage of the funnel.', 'planned', 16, true),
('UGC Creator Business Model', 'Build a profitable business creating user-generated content for brands.', 'planned', 13, true),
('The Analytics Dashboard Toolkit', 'Track and optimize your business metrics with custom dashboards.', 'planned', 8, true),
('WhatsApp Marketing for Business', 'Leverage WhatsApp for customer engagement and sales.', 'planned', 20, true),
('The No-Code App Builder Guide', 'Build functional apps without coding using no-code tools.', 'planned', 22, true),
('Customer Retention Strategies', 'Reduce churn and increase lifetime value with proven retention tactics.', 'planned', 15, true),
('The Solopreneur Tax Guide', 'Navigate taxes, deductions, and financial planning as a solopreneur.', 'planned', 24, true),
('Video Sales Letter Templates', 'High-converting VSL templates and scripts for digital products.', 'planned', 11, true),
('The Joint Venture Marketing Playbook', 'Partner with complementary businesses for explosive growth.', 'planned', 9, true),
('Automation Workflows for Creators', 'Save 10+ hours per week with automated business workflows.', 'planned', 26, true),
('The Digital Product Pricing Guide', 'Price your digital products for maximum revenue and conversions.', 'planned', 18, true),
('Reddit Marketing for Businesses', 'Authentically market your business on Reddit without getting banned.', 'planned', 12, true),
('The Coaching Business Toolkit', 'Launch and scale a profitable online coaching business.', 'planned', 21, true);
