
-- Insert bundle items into visionaire_items
INSERT INTO visionaire_items (type, title, category, thumbnail_url, is_active, content, tags, source_url, slug, format) VALUES
('bundle', 'Attract Love', 'bundles', 'https://entrepedia-products.com/covers/1772629894364-Book-Cover.jpg', true, '{"description": "Rewire your patterns, refine your standards, and build a relationship that actually lasts. A comprehensive collection of guides on love, dating, and relationships.", "item_count": 5}', ARRAY['relationships','self-improvement','dating','love'], 'https://www.entrepedia.co/library/bundles', 'attract-love-bundle', 'bundle'),
('bundle', 'Humanize Your AI Copy', 'bundles', 'https://entrepedia-products.com/covers/1772201302844-Book-Cover.jpg', true, '{"description": "Learn practical techniques to guide, refine, and edit AI outputs. A bundle of resources for making AI-generated content sound natural and human.", "item_count": 6}', ARRAY['ai','copywriting','content-creation','marketing'], 'https://www.entrepedia.co/library/bundles', 'humanize-ai-copy-bundle', 'bundle'),
('bundle', 'How to Build a Consistent Visual Identity', 'bundles', 'https://entrepedia-products.com/covers/1771393353880-Book-Cover.jpg', true, '{"description": "Learn a step-by-step process for creating a complete brand kit. Everything you need to establish a professional visual identity.", "item_count": 6}', ARRAY['branding','design','visual-identity','business'], 'https://www.entrepedia.co/library/bundles', 'visual-identity-bundle', 'bundle'),
('bundle', 'Content Marketing for Small Businesses', 'bundles', 'https://entrepedia-products.com/covers/1763998926601-Book-Cover.jpg', true, '{"description": "Complete content marketing toolkit for small business owners. From strategy to execution, learn how to grow with content.", "item_count": 5}', ARRAY['content-marketing','small-business','marketing','growth'], 'https://www.entrepedia.co/library/bundles', 'content-marketing-small-biz-bundle', 'bundle'),
('bundle', 'Confidence That Shows Before You Speak', 'bundles', 'https://entrepedia-products.com/covers/1759137036394-Book-Cover.jpg', true, '{"description": "Build unshakable confidence with this collection of guides on body language, communication, and personal presence.", "item_count": 4}', ARRAY['confidence','communication','self-improvement','personal-development'], 'https://www.entrepedia.co/library/bundles', 'confidence-bundle', 'bundle'),
('bundle', 'Atomic Execution', 'bundles', 'https://entrepedia-products.com/covers/1755071343800-Book-Cover.jpg', true, '{"description": "Master the art of getting things done. Productivity frameworks, execution strategies, and time management systems.", "item_count": 5}', ARRAY['productivity','execution','time-management','business'], 'https://www.entrepedia.co/library/bundles', 'atomic-execution-bundle', 'bundle'),
('bundle', 'Digital Detox for Founders', 'bundles', 'https://entrepedia-products.com/covers/1767881607041-Book-Cover.jpg', true, '{"description": "Break free from constant distraction and restore deep focus. A curated bundle for entrepreneurs who need to disconnect to perform.", "item_count": 4}', ARRAY['wellness','founders','focus','mental-health'], 'https://www.entrepedia.co/library/bundles', 'digital-detox-founders-bundle', 'bundle'),
('bundle', 'Mindfulness at Work', 'bundles', 'https://entrepedia-products.com/covers/1760359111894-Book-Cover.jpg', true, '{"description": "Build lasting focus, resilience, and balance through mindful work habits. A comprehensive mindfulness collection for professionals.", "item_count": 5}', ARRAY['mindfulness','wellness','productivity','work-life-balance'], 'https://www.entrepedia.co/library/bundles', 'mindfulness-at-work-bundle', 'bundle'),
('bundle', 'The Brand Evolution System for Modern Creators', 'bundles', 'https://entrepedia-products.com/covers/1768241246342-Book-Cover.jpg', true, '{"description": "Transform your creator brand with this bundle of guides on brand strategy, positioning, and audience building.", "item_count": 6}', ARRAY['branding','creators','marketing','strategy'], 'https://www.entrepedia.co/library/bundles', 'brand-evolution-bundle', 'bundle'),
('bundle', 'Agency Growth Blueprint', 'bundles', 'https://entrepedia-products.com/covers/1769612344758-Book-Cover.jpg', true, '{"description": "Scale your agency with proven frameworks. From client acquisition to team building, everything you need to grow.", "item_count": 5}', ARRAY['agency','growth','business','scaling'], 'https://www.entrepedia.co/library/bundles', 'agency-growth-bundle', 'bundle'),
('bundle', 'Turn Sales Into Predictable Growth', 'bundles', 'https://entrepedia-products.com/covers/1758020723586-Book-Cover.jpg', true, '{"description": "A proven system to break the feast-or-famine cycle and create predictable sales growth. Complete sales methodology bundle.", "item_count": 5}', ARRAY['sales','growth','revenue','business'], 'https://www.entrepedia.co/library/bundles', 'predictable-growth-bundle', 'bundle'),
('bundle', 'The Smart Homebuyer''s Playbook', 'bundles', 'https://entrepedia-products.com/covers/1764597193255-Book-Cover.jpg', true, '{"description": "Gain a clear step-by-step understanding of the home buying process. A complete real estate education bundle.", "item_count": 4}', ARRAY['real-estate','homebuying','finance','education'], 'https://www.entrepedia.co/library/bundles', 'smart-homebuyer-bundle', 'bundle'),
('bundle', 'AI-Ready Change Management', 'bundles', 'https://entrepedia-products.com/covers/1760362115332-Book-Cover.jpg', true, '{"description": "Lead change with confidence by making your team AI-ready and adaptable. A bundle of guides for modern leadership.", "item_count": 5}', ARRAY['ai','leadership','change-management','business'], 'https://www.entrepedia.co/library/bundles', 'ai-change-management-bundle', 'bundle'),
('bundle', 'The Neuroscience of Peak Productivity', 'bundles', 'https://entrepedia-products.com/covers/1768932212304-Book-Cover.jpg', true, '{"description": "Actionable methods to enter and sustain flow for maximum focus and output. Science-backed productivity bundle.", "item_count": 5}', ARRAY['neuroscience','productivity','focus','performance'], 'https://www.entrepedia.co/library/bundles', 'peak-productivity-bundle', 'bundle'),
('bundle', 'The Psychology of Closing', 'bundles', 'https://entrepedia-products.com/covers/1769609972240-Book-Cover.jpg', true, '{"description": "Master the psychology behind closing deals. A complete sales psychology collection for entrepreneurs and sales professionals.", "item_count": 4}', ARRAY['sales','psychology','closing','negotiation'], 'https://www.entrepedia.co/library/bundles', 'psychology-closing-bundle', 'bundle');
